### PR TITLE
Add layer shell support

### PR DESCRIPTION
**Pull request by HackedOS**
This PR adds a focus target to allow different focus types, adds the actual layer shell implementation

### CODE REVIEW

**Comment by HackedOS** [comment]
@Insert5StarName @electron271 should i trigger a retile on layer shell window open/close, rn when a layer shell window reserves space, user needs to manually trigger a retile by opening and closing a window for example

**Comment by electron271** [comment]
sure why not

**Comment by Insert5StarName** [comment]
> @Insert5StarName @electron271 should i trigger a retile on layer shell window open/close, rn when a layer shell window reserves space, user needs to manually trigger a retile by opening and closing a window for example

yes you should.

**Comment by electron271** [comment]
assign labels lmao

**Review by Insert5StarName — CHANGES_REQUESTED** [review]
Contains Commits from Grand Rename?

**Comment by HackedOS** [comment]
> Contains Commits from Grand Rename?

i merged the rename into the pr i didnt expect this but its fine

**Review by Insert5StarName — APPROVED** [review]
OK to merge once the rename thing is sorted out (if it doesnt affect any other commits)

**Review by Insert5StarName — APPROVED** [review]
Ok to merge now

**Pull request merged**
