### PR TITLE
made a pkgbuild for when it get's to a stable release

### PR DESCRIPTION
**Pull request by killertofus**

### CODE REVIEW

**Review by killertofus — COMMENTED** [review]
this is for the git version

**Review by electron271 — CHANGES_REQUESTED** [review]

**Comment by electron271** [comment]
this also seems too premature to add a pkgbuild, i think it would be best to take this and revise this once we have a stable release

its likely some changes will happen that break this pkgbuild

**Comment by killertofus** [comment]
fair, when it gets to a "stable" release i will edit the pkgbuild

**Comment by killertofus** [comment]
> I may be wrong about this but I don't think it's common to have the PKGBUILD be part of the main repository. I think it would make more sense to have a separate repo for maintaining a PKGBUILD. Please correct me if I'm wrong.

[swayfx](https://github.com/WillPower3309/swayfx/blob/master/build-scripts/aur/PKGBUILD) has it and [easyeffects](https://github.com/wwmm/easyeffects) has it as well, I don't see the harm in having it in the main branch

**Pull request closed without merging**
