### PR TITLE
Symlink latest.log rather than appending to it

### LINKED ISSUE #83: `latest.log` has all the logs from all the runs, not just the latest.
It looks like `latest.log` is getting appended to rather than overwritten.

### PR DESCRIPTION
**Pull request by mfdorst**
Fixes #83.

### CODE REVIEW

**Review by HackedOS — APPROVED** [review]
lgtm, didnt expect this approach but this is cool bcz it would have less writes to diska nd therefore be more efficient aswell. overall great solution, one that i did not think of lol

**Review by HackedOS — CHANGES_REQUESTED** [review]
please fix clippy

**Comment by mfdorst** [comment]
I'm having some sort of weird issue with clippy on nixos. I'm gonna fix the error I see in the CI but I can't run clippy locally so hopefully it's just that one issue.

**Review by HackedOS — APPROVED** [review]
Lgtm

**Pull request merged**
