### PR TITLE
ci: change order of tasks

### PR DESCRIPTION
**Pull request by electron271**
in my opinion it should be in this order:
- check
- clippy
- format
- build

check and clippy are where most of the errors are caught, format and build usually have less errors (format was originally first)

### CODE REVIEW

**Comment by HackedOS** [comment]
write a description

**Comment by electron271** [comment]
i will also redo it but in my opinion it should be in this order:
- check
- clippy
- format
- build

check and clippy are where most of the errors are caught, format and build usually have less errors (format was originally first)

small change however but though i would put it

**Comment by electron271** [comment]
image
based on this check only runs when one of them is finished

**Comment by HackedOS** [comment]
In my opinion check needs to be run first then clippy, check will tell us if the code compiles or not, clippy is only for following best practices the code will still work if clippy fails

**Comment by electron271** [comment]
thats the order right now

**Comment by electron271** [comment]
actually wait no one second

**Comment by electron271** [comment]
check, format, and clippy will all run at once and build will only run if format and clippy succeed

**Review by HackedOS — APPROVED** [review]
lgtm

**Pull request merged**
