### PR TITLE
removed with in magmawm.nix

### PR DESCRIPTION
**Pull request by cvoges12**
Formated with the more common best practices:
https://nix.dev/guides/best-practices

### CODE REVIEW

**Review by electron271 — CHANGES_REQUESTED** [review]
ci fails

**Comment by cvoges12** [comment]
Oh, I see. Quick fix. Sec

**Comment by cvoges12** [comment]
@electron271 Fixed

**Comment by HackedOS** [comment]
will merge after CI success

**Comment by mfdorst** [comment]
Hold on just a second. This is not a common best practice. In fact this is the first time I've seen anyone do this. You linked a best practices guide but the example shown is using `with (import <nixpkgs> {});` which is not what we have here.

**Comment by mfdorst** [comment]
I think you need to provide stronger evidence for why it is a good idea to replace the ubiquitous `with pkgs;` statement with `inherit`. If this is such a good idea why is nobody else doing it?

**Comment by mfdorst** [comment]
I tested with `nil` and it couldn't detect incorrect packages in either case, so I don't think there's a benefit, unless there's some other static analysis tool that I'm unaware of that can catch that?

**Comment by electron271** [comment]
marked as invalid until this is addressed

**Comment by cvoges12** [comment]
> The stated reason for this "best practice" is
> 
> > Static analysis can’t reason about the code, because it would have to actually evaluate this file to see which names are in scope.
> 
> I tested with `nil` and it couldn't detect incorrect packages in either case, so I don't think there's a benefit. If there's some other static analysis tool for which this makes a difference I'd love to know.

Statix and such commonly have issues with `with`. It's also not always going to have an issue. But it's very likely. So the best practice is to avoid it. In fact, in the nix lang docs, they say it's a bit of a contention because of the breaking it does.

**Comment by mfdorst** [comment]
Could you link to where in the nix lang docs they say this? There may be contention, but it seems that the accepted practice at the moment is to use `with pkgs;`, as evidenced by its ubiquitous use throughout the nix documentation. Here is a random spattering of documentation pages I've visited recently:
* [NixOS Manual](https://nixos.org/manual/nixos/stable/) (used 8 times)
* [NixOS Wiki: Rust](https://nixos.wiki/wiki/Rust) (used 4 times)
* [NixOS Wiki: Python](https://nixos.wiki/wiki/Python) (used twice)
* [NixOS Wiki: Linux kernel](https://nixos.wiki/wiki/Linux_kernel) (used once)
* [NixOS Wiki: Steam](https://nixos.wiki/wiki/Steam) (used twice)

It is even used twice in the default `configuration.nix`:
```nix
  # Define a user account. Don't forget to set a password with ‘passwd’.
  # users.users.alice = {
  #   isNormalUser = true;
  #   extraGroups = [ "wheel" ]; # Enable ‘sudo’ for the user.
  #   packages = with pkgs; [
  #     firefox
  #     tree
  #   ];
  # };

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  # environment.systemPackages = with pkgs; [
  #   vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
  #   wget
  # ];
```

**Comment by cvoges12** [comment]
Some are okay with `with`, but most of us long time nix users prefer to not use it (I since 2016). You'll find that everywhere in programming. For example, inheritance is generally frowned upon now in oop. But some still use it. Preproc abuse is frowned upon in C, but people still do it. Templates in C++ are generally desired to be reduced, but sometimes you have to. With that being said, you don't have to use `with` here. It isn't necessary. So there's no reason to be adamant to keep it.

Either way, `inherit` has no contention around it. And it is 100% compatible with 100% of the linters in any part of your code. So regardless of your stance on `with`, I still think this is the better change.


Also, to clarify, the problem with `with` in linters is not that it will error out. It is that it very, very hard for the linter to find errors beyond the `with` or anything regarding the `with` while things like `inherit` are very trivial for the linter to find. So find no errors doesn't dismiss the issue. That is the expected result.

**Comment by mfdorst** [comment]
I hear you on best practices, but what I haven't seen is significant evidence that the change you've made is in fact a best practice. One source which shows a single example using channels (which we are not using) is not sufficient to show that `with` is, in general, frowned upon. I know that the nix docs are not always up to date with current best practices (they don't use flakes for instance) so I'm not telling you you're wrong, I'm just saying I'm not yet convinced. Please provide more and stronger evidence.

**Comment by mfdorst** [comment]
Closing this for now. If further arguments are presented we may consider reopening.

**Pull request closed without merging**
