### PR TITLE
move magmawm.nix into base dir

### PR DESCRIPTION
**Pull request by electron271**
a whole folder for it is redundant

confirmed by nixos goddess to be fine

### CODE REVIEW

**Comment by nixos-goddess** [comment]
You need to change flake.nix because it still calls on the ./nix/magmawm.nix

**Comment by electron271** [comment]
done (i think)

**Comment by HackedOS** [comment]
fix CI

**Comment by electron271** [comment]
ci fixed

**Review by HackedOS — APPROVED** [review]
Lgtm

**Pull request merged**
